name: Scruffy
on:
  workflow_dispatch:
  schedule:
    # Run the GC every Monday at 9am
    - cron: "0 9 * * 1"

permissions: read-all

jobs:
  scruffy:
    name: scruffy
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29
        with:
          fetch-depth: 0
      - uses: docker://quay.io/cilium/scruffy:v0.0.1@sha256:15e3926d8e74aa6a278cc07fb61d5888322fabdae49637384dc6a3fb32452969
        with:
          entrypoint: scruffy
          args: --git-repository=./
        env:
          QUAY_TOKEN: ${{ secrets.SCRUFFY_QUAY_TOKEN }}
